// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyTrace.Infrastructure.Data;

#nullable disable

namespace MoneyTrace.Infrastructure.Migrations
{
    [DbContext(typeof(MoneyTraceDbContext))]
    [Migration("20260302062406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MoneyTrace.Domain.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.BankTransactionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Interest")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BankTransactionId");

                    b.ToTable("BankTransactionDetail");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.CashflowItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashflowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CashflowId");

                    b.ToTable("CashflowItem");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Counterparties");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasDiscriminator().HasValue("Transaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.TransferTransactionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransferTransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TransferTransactionId");

                    b.ToTable("TransferTransactionDetail");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.BankTransaction", b =>
                {
                    b.HasBaseType("MoneyTrace.Domain.Entities.Transaction");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualInterestAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestPercentage")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterestPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClose")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WithdrawDateUtc")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("BankTransaction");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.Cashflow", b =>
                {
                    b.HasBaseType("MoneyTrace.Domain.Entities.Transaction");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Cashflow");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.ExchangeTransaction", b =>
                {
                    b.HasBaseType("MoneyTrace.Domain.Entities.Transaction");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetCurrencyId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ExchangeTransaction");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.TransferTransaction", b =>
                {
                    b.HasBaseType("MoneyTrace.Domain.Entities.Transaction");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransferType")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TransferTransaction");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.BankTransactionDetail", b =>
                {
                    b.HasOne("MoneyTrace.Domain.Entities.BankTransaction", null)
                        .WithMany("Details")
                        .HasForeignKey("BankTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.CashflowItem", b =>
                {
                    b.HasOne("MoneyTrace.Domain.Entities.Cashflow", null)
                        .WithMany("Items")
                        .HasForeignKey("CashflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.TransferTransactionDetail", b =>
                {
                    b.HasOne("MoneyTrace.Domain.Entities.TransferTransaction", null)
                        .WithMany("Details")
                        .HasForeignKey("TransferTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.BankTransaction", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.Cashflow", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MoneyTrace.Domain.Entities.TransferTransaction", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
